<a href="https://colab.research.google.com/github/Komal05010/CSE-AIML-Practicals/blob/main/Practical-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [8]:
uploaded = files.upload()

Saving preprocessed_dataset.xlsx to preprocessed_dataset.xlsx


In [9]:
df = pd.read_excel("preprocessed_dataset.xlsx")

display(df.head())

,ROLL NO.,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT,GENDER_Male
0,-1.452221,-1.114072,-1.285932,-1.086620,-1.254576,-1.134590,C,PASS,True
1,-1.406793,-1.114072,-0.382744,0.064141,-0.373918,-0.730562,B,PASS,False
2,-1.361364,-0.462974,-0.563382,-0.472881,-0.550050,-0.488145,B,PASS,True
3,-1.315936,1.246160,0.972037,0.984749,1.211265,0.804744,A,PASS,True
4,-1.270508,-1.114072,-1.285932,-1.086620,-1.254576,-1.134590,C,PASS,True


In [10]:
print(df.columns.tolist())

['ROLL NO.', 'SOFTWARE ENGINEER', 'TOC', 'COMPUTER NETWORK', 'MACHINE LEARNING', 'DATA WAREHOUSE', 'GRADE', 'RESULT', 'GENDER_Male']


In [11]:
print(df["RESULT"].value_counts())

RESULT
PASS    58
FAIL     3
Name: count, dtype: int64


In [12]:
df["RESULT"] = df["RESULT"].astype("string").str.strip().str.upper()

print(df["RESULT"].unique())

<StringArray>
['PASS', 'FAIL']
Length: 2, dtype: string


In [13]:
print("Numerical columns:")
print(df.select_dtypes(include=np.number).columns.tolist())

Numerical columns:
['ROLL NO.', 'SOFTWARE ENGINEER', 'TOC', 'COMPUTER NETWORK', 'MACHINE LEARNING', 'DATA WAREHOUSE']


In [14]:
features = [
    "ROLL NO.",
    "SOFTWARE ENGINEER",
    "TOC",
    "COMPUTER NETWORK",
    "MACHINE LEARNING",
    "DATA WAREHOUSE"
]

X = df[features]
y = df["RESULT"]

In [15]:
X = X.fillna(X.median())

print(X.isnull().sum())

ROLL NO.             0
SOFTWARE ENGINEER    0
TOC                  0
COMPUTER NETWORK     0
MACHINE LEARNING     0
DATA WAREHOUSE       0
dtype: int64


In [16]:
y = y.map({
    "FAIL": 0,
    "PASS": 1
})

print(y.value_counts())

RESULT
1    58
0     3
Name: count, dtype: int64


In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
from sklearn.metrics import pairwise_distances

euclidean_matrix = pairwise_distances(
    X_test_scaled,
    X_train_scaled,
    metric="euclidean"
)

manhattan_matrix = pairwise_distances(
    X_test_scaled,
    X_train_scaled,
    metric="manhattan"
)

minkowski_matrix = pairwise_distances(
    X_test_scaled,
    X_train_scaled,
    metric="minkowski",
    p=3
)

In [28]:
print("Euclidean Distance Matrix:")
display(pd.DataFrame(euclidean_matrix))

print("Manhattan Distance Matrix:")
display(pd.DataFrame(manhattan_matrix))

print("Minkowski Distance Matrix (p=3):")
display(pd.DataFrame(minkowski_matrix))

Euclidean Distance Matrix:


,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47
0,1.690170,0.819185,2.758777,3.483806,0.530016,2.593978,3.426911,0.807897,0.431150,1.978717,2.315290,2.716180,3.028683,2.509474,2.956733,2.470654,3.013730,3.273390,3.123625,3.402828,3.602702,3.480603,2.081613,0.599786,1.026753,2.685891,1.473657,1.078852,3.118956,1.201742,1.336565,3.480603,0.484195,3.260006,3.045177,2.135027,3.517790,3.299967,4.031337,1.629196,1.496190,2.761625,2.686908,1.962391,1.640015,2.060631,1.700796,3.458108
1,2.772339,1.268992,2.205083,2.644896,1.911102,3.434650,4.335645,1.661336,1.301534,2.790340,3.651848,2.421874,4.101658,3.408572,3.831824,3.398742,2.452738,2.632003,3.083655,2.496405,3.109809,2.711528,3.466918,1.517829,2.331707,2.798227,2.046599,1.269270,2.195649,2.432125,1.402587,2.664502,1.813788,2.999807,2.079053,1.771985,2.871351,2.849872,5.046726,2.155922,2.890400,4.129850,4.056963,2.300183,1.180597,3.409704,2.298379,2.483154
2,3.750518,3.743085,0.812983,0.732955,3.783025,5.960833,6.860232,3.955969,3.618083,3.473948,5.651560,1.018622,6.517707,5.908210,5.885229,5.883617,0.678539,0.384957,1.565362,0.930955,0.524505,0.474265,5.288742,3.428693,3.783025,2.352109,4.522367,2.496650,1.916237,3.679516,3.963080,0.646725,3.808735,1.102052,1.237180,4.025294,0.043115,0.651017,7.223622,4.464050,4.712242,5.752783,5.729957,2.212568,2.054055,4.821432,4.661768,1.344381
3,1.970951,0.517380,2.821734,3.481938,0.708609,2.452151,3.320849,0.594487,0.129345,2.263949,2.417028,2.835712,2.983230,2.384508,2.833124,2.354698,3.058730,3.318790,3.307742,3.385576,3.704209,3.501105,2.200135,0.566309,1.300702,2.717199,1.228021,1.165808,3.015009,1.495973,1.034760,3.486207,0.570553,3.406400,3.004308,1.960271,3.574665,3.402857,4.032950,1.438306,1.664959,2.950694,2.867302,2.179181,1.620057,2.302216,1.484268,3.403109
4,2.906306,2.264554,4.969860,5.655013,1.977984,0.948530,1.336686,1.901315,2.223550,3.419956,1.034760,4.895088,0.831074,0.776070,1.818557,0.689840,5.209710,5.469605,5.197162,5.566962,5.800311,5.670769,1.234305,2.353517,2.284971,4.498543,1.736183,3.259059,5.079886,2.585387,2.417028,5.658956,1.923187,5.417097,5.171317,3.182940,5.722977,5.509576,2.185621,1.871815,1.464117,2.026405,1.897060,3.972758,3.769488,2.195555,1.964093,5.554007
5,1.581507,2.441857,1.843526,2.763433,1.883119,4.288806,5.059762,2.479637,2.115108,1.261833,3.448932,1.473006,4.559773,4.185267,4.488979,4.135222,2.177483,2.318335,1.522648,2.766333,2.306266,2.635347,3.111356,1.874074,1.592134,2.452482,3.178991,1.251831,3.047373,1.401729,2.901107,2.718674,2.014283,1.816613,2.628435,3.066158,2.467784,2.024406,5.294332,3.155736,2.521455,3.405268,3.394606,0.519703,1.672441,2.476826,3.411952,3.048201
6,2.546610,2.060784,1.178010,1.751064,2.111483,4.204854,5.100607,2.214610,1.930853,2.493372,4.017664,1.237210,4.791803,4.151465,4.229208,4.127215,1.394772,1.525627,1.958502,1.699146,1.987319,1.738278,3.648487,1.664720,2.274242,1.818830,2.793505,0.969431,1.658953,2.291076,2.325249,1.742551,2.104870,1.910808,1.427627,2.457786,1.801300,1.748917,5.591322,2.743826,3.113167,4.280435,4.233931,1.398229,0.516908,3.409556,3.079691,1.833887
7,2.695633,2.623003,0.613795,1.333022,2.586940,4.783394,5.671328,2.780871,2.468568,2.580991,4.469175,0.644841,5.324521,4.723955,4.705494,4.696328,0.788560,0.983006,1.458085,1.381892,1.362723,1.246546,4.109395,2.251283,2.632527,1.668774,3.380517,1.346542,1.720812,2.579556,2.897760,1.299122,2.610189,1.317901,1.227508,3.117987,1.216356,1.184171,6.050054,3.321665,3.537868,4.633567,4.600351,1.307575,0.965831,3.722220,3.547687,1.609968
8,2.237370,0.812734,2.274408,2.841524,1.167433,2.954105,3.864695,0.957477,0.737174,2.443328,3.039703,2.360598,3.594210,2.908445,3.079391,2.889207,2.479609,2.725514,2.961374,2.748019,3.190146,2.880508,2.744056,0.644379,1.670490,2.244780,1.529981,0.793776,2.322652,1.850912,1.133635,2.851972,1.054489,2.988710,2.348967,1.917854,2.994417,2.917300,4.510346,1.571143,2.237288,3.527946,3.452045,1.96

Manhattan Distance Matrix:


,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47
0,2.832756,0.819185,6.436346,7.863150,0.936863,6.263842,8.366836,1.368013,0.431150,3.100260,5.574002,6.536225,7.216381,6.091382,5.726766,6.005152,6.885342,7.520479,7.398526,7.853807,8.682405,7.776919,4.766667,1.293901,1.626703,5.856652,2.812821,2.392266,7.457359,1.504077,1.336565,7.776919,0.721288,7.891705,7.161757,4.027402,8.208070,7.978500,8.221532,2.604911,3.557237,6.565647,6.436302,4.400667,3.743391,4.419538,2.894141,8.216603
1,4.931101,2.441211,4.814320,5.896204,4.024799,7.885868,9.988862,3.162499,2.656786,4.822629,8.661938,4.914200,9.097096,7.713408,7.348791,7.627178,5.263317,5.898453,5.776500,5.541942,7.060380,6.154894,7.854603,3.111382,4.714639,6.173135,4.434847,2.419141,4.537989,4.592013,2.958591,5.982434,3.809224,6.269679,4.418741,4.009732,6.586044,6.356475,11.050777,4.226936,6.645173,9.653583,9.524238,3.942564,2.446815,7.507474,4.516167,5.128667
2,8.973359,9.070370,1.814839,0.732955,8.756898,14.515027,16.618021,9.619198,8.682335,8.347931,12.704196,2.491029,15.467565,14.342567,13.977950,14.256337,1.365842,0.730706,3.353330,1.255783,0.603540,0.474265,11.896862,8.188825,8.756898,3.827343,11.064006,5.858919,3.208266,8.634271,9.587750,0.646725,8.972473,2.170310,2.210418,8.792421,0.043115,1.134984,16.472716,10.856095,10.687432,13.695841,13.566496,5.402658,5.025174,11.549732,11.145326,1.586722
3,3.134561,0.517380,6.738151,7.820035,1.238668,5.962037,8.065031,1.066208,0.129345,3.402065,5.875807,6.838030,6.914576,5.789577,5.424961,5.703347,7.187148,7.822284,7.700331,7.552002,8.984210,8.078725,5.068473,1.164556,1.928508,6.158457,2.511016,2.694071,7.155554,1.805882,1.034760,7.906265,1.023093,8.193510,6.859952,3.725597,8.509875,8.280305,8.264647,2.303106,3.859043,6.867452,6.738107,4.702472,3.527816,4.721343,2.592336,7.914798
4,6.576427,5.358427,11.751658,12.833541,4.809599,0.948530,3.051525,4.464679,4.970392,7.805466,1.034760,11.851537,1.901069,0.776070,3.933898,0.689840,12.200654,12.835791,12.713837,12.479279,13.997717,13.092231,1.928325,5.377672,5.499439,9.739154,4.227091,7.707578,11.996601,6.139445,5.875807,12.919771,4.594024,13.207017,11.700999,6.843455,13.523381,13.293812,3.423600,4.176311,3.223985,2.026405,1.897060,9.715979,8.541322,4.086285,4.232001,12.755845
5,3.333730,4.716725,4.263406,6.552510,4.403253,10.161382,12.264376,5.265553,4.328690,2.528376,8.178091,3.328526,11.113921,9.988922,9.624306,9.902692,4.971093,5.519999,3.500986,6.543168,5.216015,6.293820,7.284527,3.835180,3.713413,5.383001,6.710361,2.202156,6.146720,3.073406,5.234105,6.466280,4.618828,3.994165,5.851118,5.445941,5.862670,4.684571,12.119072,6.502451,5.988867,7.876286,7.746941,0.992081,2.432751,5.730177,6.791681,6.905964
6,5.704403,4.766653,2.656739,4.001912,4.798101,10.211310,12.314304,5.315481,4.378618,5.078975,9.435240,2.588757,11.163849,10.038850,9.674234,9.952620,2.937874,3.573011,3.451057,3.992570,4.734937,3.829451,8.627905,3.885108,5.487941,3.844167,6.760289,1.813892,3.596121,5.365315,5.284033,3.915681,4.668756,3.944237,3.300519,4.656565,4.260602,4.031032,12.169000,6.552379,7.418475,10.426885,10.297540,2.133701,0.721457,8.280776,6.841609,4.355365
7,6.467360,6.219450,1.036081,3.238955,5.905978,11.664107,13.767101,6.768278,5.831415,5.841931,10.198197,1.135960,12.616646,11.491647,11.127031,11.405417,1.657538,2.206444,1.998261,3.229613,3.282140,2.980265,9.390862,5.337905,6.250898,3.078021,8.213086,3.007999,2.833164,6.128272,6.736830,3.152725,6.121553,2.491440,2.537563,6.277223,2.807805,2.578235,13.621797,8.005176,8.181432,11.189842,11.060497,2.896658,2.174254,9.043732,8.294406,3.592408
8,3.879062,1.726626,5.528904,6.610788,2.792835,7.171283,9.274278,2.275454,1.424821,3.916538,7.429973,5.628784,8.123822,6.998823,6.634207,6.912593,5.977901,6.613038,6.491084,6.256526,7.774964,6.869478,6.622639,1.362461,3.482675,5.202060,3.720262,1.484825,5.601387,3.360049,2.244007,6.697018,2.577259,6.984264,5.305786,3.752727,7.300628,7.07

Minkowski Distance Matrix (p=3):


,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47
0,1.577275,0.819185,2.116436,2.688706,0.450162,1.951447,2.550560,0.705869,0.431150,1.874332,1.745074,2.047312,2.291336,1.877791,2.427091,1.846528,2.334307,2.524094,2.390809,2.609325,2.712353,2.688499,1.625509,0.486688,0.937298,2.139579,1.306021,0.857627,2.364765,1.170408,1.336565,2.688499,0.433040,2.443142,2.326890,1.783673,2.694841,2.478016,3.402060,1.431173,1.139601,2.113560,2.039229,1.568670,1.279004,1.726449,1.461692,2.628297
1,2.451914,1.074485,1.779568,2.110927,1.538451,2.684012,3.360707,1.407527,1.082182,2.615492,2.791031,1.994345,3.192944,2.677529,3.273104,2.675709,1.957333,2.055476,2.697966,1.998568,2.435039,2.138515,2.715859,1.248900,1.929696,2.253110,1.661309,1.066113,1.815573,2.097424,1.134394,2.117966,1.470785,2.502619,1.687584,1.378181,2.236374,2.270610,4.084394,1.812176,2.248385,3.189611,3.120459,2.118155,0.970709,2.751735,1.936895,2.032435
2,2.840388,2.804506,0.647389,0.732955,2.886525,4.445592,5.136298,2.953695,2.732709,2.617022,4.327335,0.756871,4.938125,4.416769,4.499047,4.404233,0.556689,0.317574,1.325691,0.908278,0.518175,0.474265,4.062230,2.596665,2.886525,2.162826,3.358865,1.906381,1.792749,2.809579,2.972305,0.646725,2.891918,0.958441,1.140618,3.230071,0.043115,0.560968,5.609830,3.337955,3.606235,4.349502,4.342462,1.646304,1.525622,3.634283,3.533795,1.336894
3,1.871679,0.517380,2.139522,2.688569,0.603405,1.832307,2.483227,0.496293,0.129345,2.170888,1.806678,2.131393,2.279053,1.784739,2.352403,1.766368,2.346020,2.536043,2.579175,2.607318,2.773229,2.691161,1.703328,0.473117,1.225515,2.145243,1.040465,0.901377,2.302511,1.469895,1.034760,2.688931,0.477240,2.569096,2.317074,1.638026,2.713586,2.540938,3.402145,1.274960,1.299443,2.311294,2.222743,1.803924,1.275483,1.992761,1.245940,2.610773
4,2.318662,1.723985,3.771053,4.327502,1.476847,0.948530,1.071020,1.445209,1.714958,2.710064,1.034760,3.666296,0.653576,0.776070,1.421976,0.689840,3.968069,4.158540,3.860286,4.260903,4.353512,4.329222,1.120323,1.810522,1.728600,3.571713,1.296199,2.475476,3.857334,1.982680,1.806678,4.327813,1.451742,4.036750,3.962135,2.562281,4.340496,4.135405,2.034590,1.434420,1.212782,2.026405,1.897060,2.951616,2.884969,2.014585,1.544135,4.244867
5,1.286018,2.181846,1.428446,2.110421,1.451288,3.298124,3.795025,2.088358,1.825840,1.037088,2.618530,1.172747,3.399320,3.192122,3.587933,3.142001,1.701052,1.764815,1.195907,2.124148,1.802456,2.000738,2.389911,1.605704,1.230445,1.906394,2.703163,1.148046,2.639646,1.123599,2.675367,2.070465,1.583213,1.448938,2.126390,2.761736,1.886786,1.568068,4.193591,2.667670,1.918095,2.607327,2.605805,0.446886,1.575443,1.904537,2.896016,2.431370
6,2.015541,1.603158,0.917264,1.356101,1.639945,3.146236,3.831438,1.679057,1.530602,2.068372,3.063024,1.014289,3.672927,3.116770,3.311918,3.104689,1.111925,1.171690,1.799283,1.302918,1.506415,1.354298,2.772950,1.278475,1.715266,1.484185,2.097889,0.869640,1.375330,1.757214,1.827697,1.354676,1.639319,1.581236,1.098121,2.092288,1.373400,1.351560,4.442552,2.086824,2.362840,3.193783,3.163778,1.318872,0.466306,2.551098,2.470013,1.389032
7,2.036623,1.995930,0.541350,0.997204,1.987330,3.564590,4.241911,2.076359,1.889098,1.999551,3.425093,0.581891,4.045183,3.527744,3.605509,3.511890,0.645647,0.761912,1.426236,1.065507,1.027765,0.944677,3.162122,1.726756,1.998523,1.486837,2.528021,1.069095,1.614412,1.962971,2.245424,0.973373,1.991818,1.151866,1.040931,2.590625,0.935120,0.926920,4.744651,2.504116,2.706995,3.479280,3.464179,1.065331,0.770288,2.783006,2.728298,1.308141
8,2.064217,0.640905,1.699921,2.165618,0.889352,2.208385,2.910337,0.724493,0.605780,2.340561,2.259642,1.805071,2.759638,2.186788,2.504572,2.179209,1.867121,2.039210,2.462545,2.103064,2.379029,2.176128,2.063256,0.521198,1.442473,1.740908,1.143906,0.691292,1.749232,1.677147,0.952219,2.167814,0.783964,2.331772,1.805186,1.601363,2.230979,2.186267,3.646540,1.277971,1.682234,2.694282,2.617349,1.83

In [29]:
K = 5

euclidean_neighbours = np.argsort(
    euclidean_matrix,
    axis=1
)[:, :K]

In [30]:
print("Nearest neighbours using Euclidean distance:")
print(euclidean_neighbours)

Nearest neighbours using Euclidean distance:
[[ 8 32  4 23  7]
 [44  1 27  8 30]
 [36 17 21 20 31]
 [ 8  1 23 32  7]
 [15 13 12  5 10]
 [43 27  9 29 11]
 [44 27  2 11 16]
 [ 2 11 16 44 17]
 [23  8 27  1  7]
 [39 26  7 46  1]
 [26  5 13 39 15]
 [36 20 37 17 21]
 [38 12  6 10 42]]


In [32]:
import numpy as np

euclidean_labels = np.asarray(y_train)[euclidean_neighbours]

print("Classes of nearest neighbours:")
print(euclidean_labels)

Classes of nearest neighbours:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 1 1]]


In [34]:
euclidean_predictions = []

for neighbours in euclidean_labels:
    prediction = np.bincount(neighbours).argmax()
    euclidean_predictions.append(prediction)

print("Euclidean predictions:")
print(euclidean_predictions)

Euclidean predictions:
[np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1)]


In [35]:
from sklearn.metrics import accuracy_score

euclidean_accuracy = accuracy_score(
    y_test,
    euclidean_predictions
)

print("Euclidean KNN Accuracy:", euclidean_accuracy)
print("Euclidean KNN Accuracy (%):", euclidean_accuracy * 100)

Euclidean KNN Accuracy: 0.9230769230769231
Euclidean KNN Accuracy (%): 92.3076923076923


In [36]:
K = 5

manhattan_neighbours = np.argsort(
    manhattan_matrix,
    axis=1
)[:, :K]

print("Manhattan nearest neighbours:")
print(manhattan_neighbours)

Manhattan nearest neighbours:
[[ 8 32  1  4 23]
 [27  1 44  8 30]
 [36 21 20 31 17]
 [ 8  1 32 30  7]
 [15 13  5 10 42]
 [43 27 44  9 29]
 [44 27 43 11  2]
 [ 2 11 16 18 44]
 [23  8 27  1 30]
 [39 46  7 26 14]
 [26 40  5 46 13]
 [36 20 37 21 17]
 [38 12  6 10 42]]


In [37]:
manhattan_labels = np.asarray(y_train)[manhattan_neighbours]

print("Classes of Manhattan nearest neighbours:")
print(manhattan_labels)

Classes of Manhattan nearest neighbours:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 1 1]]


In [38]:
manhattan_predictions = []

for neighbours in manhattan_labels:
    prediction = np.bincount(neighbours).argmax()
    manhattan_predictions.append(prediction)

print("Manhattan predictions:")
print(manhattan_predictions)

Manhattan predictions:
[np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1)]


In [39]:
manhattan_accuracy = accuracy_score(
    y_test,
    manhattan_predictions
)

print("Manhattan KNN Accuracy:", manhattan_accuracy)
print("Manhattan KNN Accuracy (%):", manhattan_accuracy * 100)

Manhattan KNN Accuracy: 0.9230769230769231
Manhattan KNN Accuracy (%): 92.3076923076923


In [40]:
minkowski_neighbours = np.argsort(
    minkowski_matrix,
    axis=1
)[:, :K]

print("Minkowski nearest neighbours:")
print(minkowski_neighbours)

Minkowski nearest neighbours:
[[ 8 32  4 23  7]
 [44 27  1  8 30]
 [36 17 21 20 16]
 [ 8 23 32  7  1]
 [12 15 13  5 10]
 [43  9 29 27 11]
 [44 27  2 11 34]
 [ 2 11 16 17 44]
 [23  8  1 27  7]
 [26 39  7 46 15]
 [26  5 13 39 15]
 [36 20 37 17  2]
 [38 12  6 10 42]]


In [41]:
minkowski_labels = np.asarray(y_train)[minkowski_neighbours]

print("Classes of Minkowski nearest neighbours:")
print(minkowski_labels)

Classes of Minkowski nearest neighbours:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 1 1]]


In [42]:
minkowski_predictions = []

for neighbours in minkowski_labels:
    prediction = np.bincount(neighbours).argmax()
    minkowski_predictions.append(prediction)

print("Minkowski predictions:")
print(minkowski_predictions)

Minkowski predictions:
[np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1)]


In [43]:
minkowski_accuracy = accuracy_score(
    y_test,
    minkowski_predictions
)

print("Minkowski KNN Accuracy:", minkowski_accuracy)
print("Minkowski KNN Accuracy (%):", minkowski_accuracy * 100)

Minkowski KNN Accuracy: 0.9230769230769231
Minkowski KNN Accuracy (%): 92.3076923076923


In [44]:
results = pd.DataFrame({
    "Distance": [
        "Euclidean",
        "Manhattan",
        "Minkowski (p=3)"
    ],
    "Accuracy (%)": [
        euclidean_accuracy * 100,
        manhattan_accuracy * 100,
        minkowski_accuracy * 100
    ]
})

display(results)

,Distance,Accuracy (%)
0,Euclidean,92.307692
1,Manhattan,92.307692
2,Minkowski (p=3),92.307692


In [45]:
best_distance = results.loc[
    results["Accuracy (%)"].idxmax()
]

print("Best Distance Metric:", best_distance["Distance"])
print("Best Accuracy:", best_distance["Accuracy (%)"], "%")

Best Distance Metric: Euclidean
Best Accuracy: 92.3076923076923 %
